/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ArchivosBinarios;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fampa
 */
public class MenuPrincipal extends javax.swing.JFrame {
    EmpleadosManager em;
    public MenuPrincipal(EmpleadosManager em) {
        initComponents();
       setLocationRelativeTo(this);
        this.em=em;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnListarEmpNoDespedidos = new javax.swing.JButton();
        btnAgregarVenta = new javax.swing.JButton();
        btnPagarEmpleado = new javax.swing.JButton();
        btnDespedirEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, 62));

        btnSalir.setBackground(new java.awt.Color(255, 204, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 460, 40));

        btnAgregarEmpleado.setBackground(new java.awt.Color(255, 204, 0));
        btnAgregarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAgregarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarEmpleado.setText("Agregar Empleado");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 460, 40));

        btnListarEmpNoDespedidos.setBackground(new java.awt.Color(255, 204, 0));
        btnListarEmpNoDespedidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnListarEmpNoDespedidos.setForeground(new java.awt.Color(0, 0, 0));
        btnListarEmpNoDespedidos.setText("Listar Empleados No Despedidos");
        btnListarEmpNoDespedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarEmpNoDespedidosActionPerformed(evt);
            }
        });
        jPanel2.add(btnListarEmpNoDespedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 460, 40));

        btnAgregarVenta.setBackground(new java.awt.Color(255, 204, 0));
        btnAgregarVenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAgregarVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarVenta.setText("Agregar Venta a Empleado");
        btnAgregarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVentaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 460, 40));

        btnPagarEmpleado.setBackground(new java.awt.Color(255, 204, 0));
        btnPagarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPagarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnPagarEmpleado.setText("Pagar Empleado");
        btnPagarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPagarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 460, 40));

        btnDespedirEmpleado.setBackground(new java.awt.Color(255, 204, 0));
        btnDespedirEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDespedirEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnDespedirEmpleado.setText("Despedir Empleado");
        btnDespedirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespedirEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnDespedirEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 460, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        Agregar_Empleadou ae = new Agregar_Empleadou(em);
        ae.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnListarEmpNoDespedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarEmpNoDespedidosActionPerformed
            Listar_ND lnd = new Listar_ND(em);
            lnd.setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.");
    }//GEN-LAST:event_btnListarEmpNoDespedidosActionPerformed

    private void btnAgregarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVentaActionPerformed
        Agregar_Venta av = new Agregar_Venta(em);
        av.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAgregarVentaActionPerformed

    private void btnPagarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarEmpleadoActionPerformed
        PagarEmpleado pe = new PagarEmpleado(em);
        pe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPagarEmpleadoActionPerformed

    private void btnDespedirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespedirEmpleadoActionPerformed
        DespedirEmpleado de = new DespedirEmpleado(em);
        de.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDespedirEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnAgregarVenta;
    private javax.swing.JButton btnDespedirEmpleado;
    private javax.swing.JButton btnListarEmpNoDespedidos;
    private javax.swing.JButton btnPagarEmpleado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnregresarconfig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
